%YAML 1.1
---
#########################
## SHOULD BE USING MIG ##
#########################
should-be-using-mig-core-gpu:
  cluster: core
  partition: gpu


############################
## LOW CPU/GPU EFFICIENCY ##
############################
low-xpu-efficiency-core-cpu:
  cluster: core
  cluster_name: "core (cpu)"
  partitions:
    - fast
    - long
    - bigmem
  xpu: cpu
  eff_thres_pct: 60
  proportion_thres_pct: 2
  num_top_users: 15
  excluded_users: []

low-xpu-efficiency-core-gpu:
  cluster: core
  cluster_name: "core (gpu)"
  partitions:
    - gpu
  xpu: gpu
  eff_thres_pct: 15
  proportion_thres_pct: 2
  num_top_users: 15
  excluded_users: []

#######################
## EXCESS CPU MEMORY ##
#######################
excess-cpu-memory-core-cpu:
  tb_hours_per_day: 10
  ratio_threshold: 0.35
  mean_ratio_threshold: 0.35
  median_ratio_threshold: 0.35
  num_top_users: 10
  clusters:
    - core
  partition:
    - fast
    - long
    - bigmem
  combine_partitions: False
  cores_per_node: 28
  excluded_users: []
